theme:           jekyll-theme-cayman
title:           Photo of the Day
description:     Downloads Bing & NASA Photo of the Day and makes it desktop background
is_user_page:    false
is_project_page: true
show_downloads:  true
